spring:
  application:
    name: documentation
  flyway:
    enabled: true
    validate-on-migrate: false
    out-of-order: true
    baselineOnMigrate: true
    schemas: documentation
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: documentation
    password: documentation66659
    url: jdbc:postgresql://localhost:5432/documentation
    driver-class-name: org.postgresql.Driver
server:
  servlet:
    context-path: /documentation
  error:
    include-message: always
  port: 2493
springdoc:
  api-docs:
    path: /v1/openapi.json  # Path for the generated OpenAPI JSON documentation
  swagger-ui:
    path: /  # Path for the Swagger UI interface
    disable-swagger-default-url: true  # Disable the default Swagger UI URL
    doc-expansion: none  # Disable documentation expansion by default
  pre-loading-enabled: true  # Enable preloading of OpenAPI documentation
swagger:
  url:
    rent: http://localhost:2493/documentation/  # URL for Swagger documentation
jwt:
  secret: j3bhvh25hufhu6biyu5ifc5hc756u809asf2g224tg2g52ff2tf2g222fsdt22t24